--liquibase formatted.sql
--changeset michael.cawayan:SDM.CRM_SCORE_CONFIG contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE "SDM"."CRM_SCORE_CONFIG" (
    "TABLE_NAME" VARCHAR2(15 CHAR),
    "DTIME_INSERTED" DATE,
    FLAG_ACTIVE  VARCHAR2(1 CHAR)
    )
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "SDM"."CRM_SCORE_CONFIG" TO MA_TEMP
/
GRANT SELECT ON "SDM"."CRM_SCORE_CONFIG" TO SAS_SDM_RO
/
GRANT SELECT ON "SDM"."CRM_SCORE_CONFIG" TO HCPH_SDM_RO
/
GRANT SELECT ON "SDM"."CRM_SCORE_CONFIG" TO HCI_APP_SELECT
/
GRANT UPDATE ON "SDM"."CRM_SCORE_CONFIG" TO HCI_APP_UPDATE
/
GRANT INSERT ON "SDM"."CRM_SCORE_CONFIG" TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON "SDM"."CRM_SCORE_CONFIG" TO APPSUPPORT
/
GRANT SELECT ON "SDM"."CRM_SCORE_CONFIG" TO HCI_RO_SDM
/
GRANT SELECT, INSERT, UPDATE ON "SDM"."CRM_SCORE_CONFIG" TO HCI_APP_VIEWER
/
GRANT SELECT, INSERT, UPDATE ON "SDM"."CRM_SCORE_CONFIG" TO HCI_CONNECT
/