--liquibase formatted.sql
--changeset michael.cawayan:SDM.CRM_SCORE_B contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
  CREATE TABLE "SDM"."CRM_SCORE_B" (
  "ID_CUID" NUMBER(15,0) NOT NULL ENABLE, 
  "CRM_SCORE_1" NUMBER, 
  "CRM_SCORE_2" NUMBER, 
  "CRM_SCORE_3" NUMBER, 
  "CRM_SCORE_4" NUMBER, 
  "CRM_SCORE_5" NUMBER, 
  "INSUPD_DT_1" DATE, 
  "INSUPD_DT_2" DATE, 
  "INSUPD_DT_3" DATE, 
  "INSUPD_DT_4" DATE, 
  "INSUPD_DT_5" DATE, 
  "DTIME_INSERTED" DATE NOT NULL ENABLE, 
  "DTIME_UPDATED" DATE NOT NULL ENABLE, 
  "CRM_SCORE_6" NUMBER, 
  "CRM_SCORE_7" NUMBER, 
  "CRM_SCORE_8" NUMBER, 
  "CRM_SCORE_9" NUMBER, 
  "CRM_SCORE_10" NUMBER, 
  "INSUPD_DT_6" DATE, 
  "INSUPD_DT_7" DATE, 
  "INSUPD_DT_8" DATE, 
  "INSUPD_DT_9" DATE, 
  "INSUPD_DT_10" DATE,
  CONSTRAINT "PK_ID_CUID_B" PRIMARY KEY ("ID_CUID")
  ) 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "SDM"."CRM_SCORE_B" TO MA_TEMP
/
GRANT SELECT ON "SDM"."CRM_SCORE_B" TO HCI_APP_SELECT
/
GRANT SELECT ON "SDM"."CRM_SCORE_B" TO APPSUPPORT
/
GRANT SELECT ON "SDM"."CRM_SCORE_B" TO SAS_SDM_RO
/
GRANT SELECT ON "SDM"."CRM_SCORE_B" TO HCI_RO_SDM
/